from picamera import PiCamera
from time import sleep
from datetime import datetime

import array as a
import subprocess
import sys

# this data file is generated by sunrise.pl on the import system
file = open("sunrise_sunset.data", "r")
a = file.read().split(",")
file.close 

begin_limit = int(a[0]) * 60 + int(a[1])

# what time is it?
t = datetime.now()
begin_t = t.hour * 60 + t.minute

# is it too early to start?
if (begin_t < begin_limit):
    print ( "dont start yet" )
    sys.exit(0)

# what time is quitting time?
end_t = datetime(t.year, t.month, t.day, int(a[2]), int(a[3]), 0)

if (t > end_t):
	print ("dont restart")
	sys.exit(0)

thisHost = "_pi15"

image_path_header = "/home/pi/share/images/image"
icon_path_header = "/home/pi/share/images/icon_image"
fileext = thisHost + ".jpg"

# set up and turn on the camera
camera = PiCamera()
camera.rotation = 180
camera.exposure_mode = 'sports'
camera.resolution = (1280,1024)
# camera.brightness = 55

camera.start_preview()
#sleep(2)

for i in range ( (30 * 13) ):

   t = datetime.now()
   time_now = t.strftime("%Y%m%d%H%M")
   image_pathname = image_path_header + time_now + fileext
   icon_pathname  = icon_path_header  + time_now + fileext

   print (time_now + " snap: " + image_pathname)
   sleep(2)

   camera.capture(image_pathname)

   subprocess.call(['/bin/sh',  '/home/pi/datetime_image.sh', image_pathname])
   subprocess.call(['/bin/sh',  '/home/pi/make_icon.sh', image_pathname, icon_pathname]) 
   subprocess.call(['sudo', 'ln', "-f", s , '/var/www/html/myImage.jpg'])

   if (t > end_t):
       break
   sleep (118)

camera.stop_preview()

subprocess.call(['mail', '-s', '"shutting down"', 'loves.toys@gmail.com', '-A', '/var/www/html/myImage.jpg', '<', 'camera.py'])

print (t.strftime("%Y%m%d%H%M") + " closing camera collection...")

sleep (5)
